import type { NextPage } from "next";
import { signOut } from "next-auth/react";
import Head from "next/head";
import { useUnauthenticatedRedirect } from "../hooks/auth";

const Home: NextPage = () => {
  const shouldRender = useUnauthenticatedRedirect("/auth/signin");

  if (!shouldRender) return null;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <button onClick={() => signOut()}>Log out</button>
      </main>
    </>
  );
};

export default Home;
