import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.sessions.getAll.useQuery();

  if (isLoading) {
    return <p>loading...</p>;
  }

  return (
    <>
      <Head>
        <title>Sessions list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {data?.map((session) => {
          return <p key={session.id}>session.id</p>;
        })}
      </main>
    </>
  );
};

export default Home;
